spring:
  datasource:
    url: jdbc:mysql://localhost:3306/payroll # 数据库连接URL
    username: root # 数据库用户名
    password: 123456 # 数据库密码
  jpa:
    hibernate:
      ddl-auto: update # 自动更新数据库模式
    show-sql: true # 显示SQL语句
#  mvc:
#    view:
#      prefix: / # 视图前缀
#      suffix: .html # 视图后缀
#    pathmatch:
#      matching-strategy: ant_path_matcher # 路径匹配策略